import dayjs from 'dayjs';

import { formatDateOrdinal } from './format';

/**
 * Pure helpers for the New Trip wizard payload. Kept out of the page
 * component so they can be unit-tested (and so the page file only exports
 * a component, keeping react-refresh happy).
 */

export function buildDays(startDate, endDate) {
  const days = [];
  let current = dayjs(startDate);
  const last = dayjs(endDate);
  for (let i = 1; !current.isAfter(last, 'day'); i += 1) {
    days.push({
      dayId: crypto.randomUUID(),
      title: `Day ${i} — ${formatDateOrdinal(current.format('YYYY-MM-DD'))}`,
      date: current.format('YYYY-MM-DD'),
      points: [],
    });
    current = current.add(1, 'day');
  }
  return days;
}

export function routeLocations(route) {
  if (!route) return [];
  return route.split(/[→\-–>]+/).map((part, i, arr) => ({
    locationId: crypto.randomUUID(),
    name: part.trim(),
    role: i === 0 ? 'origin' : i === arr.length - 1 ? 'destination' : 'waypoint',
  }));
}

/**
 * Convert a wizard leg into a trip-level travel detail.
 *
 * This used to also push departure/arrival points onto the days. It no longer
 * does: those points are generated by the backend from this leg's times (see
 * api/app/services/detail_points.py, which is their only writer). Sending our
 * own was how the same flight ended up on the timeline twice.
 */
export function buildTravelLeg(leg) {
  if (!leg || leg.skipped) return null;
  return {
    travelDetailId: crypto.randomUUID(),
    name: leg.title || leg.route || 'Travel',
    mode: leg.mode,
    operator: leg.operator || null,
    vehicleNumber: leg.vehicleNumber || null,
    departureDateTime: leg.departureDateTime || null,
    arrivalDateTime: leg.arrivalDateTime || null,
    locations: routeLocations(leg.route),
  };
}

export function buildImportPayload({ tripDetails, outbound, returnLeg }) {
  return {
    tripId: crypto.randomUUID(),
    tripName: tripDetails.tripName,
    startDate: tripDetails.startDate,
    endDate: tripDetails.endDate,
    stays: [],
    travels: [buildTravelLeg(outbound), buildTravelLeg(returnLeg)].filter(Boolean),
    days: buildDays(tripDetails.startDate, tripDetails.endDate),
  };
}
