"""baseline: the schema as deployed from the rebuild branch

Generated with autogenerate from the models as they stood on `rebuild`
(before Phase 29). A database created by that code's `create_all` matches
this exactly, so app/migrate.py stamps such a database at 0001 instead of
re-creating its tables.

Revision ID: 0001
Revises:
Create Date: 2026-10-03 15:14:59.451870
"""

from __future__ import annotations

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

import app.db_types

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "trips",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            app.db_types.UtcDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trips_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_trips_user_id"), ["user_id"], unique=False)

    op.create_table(
        "days",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("days", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_days_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_days_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index(
            "uq_days_trip_date_live",
            ["trip_id", "date"],
            unique=True,
            sqlite_where=sa.text("is_deleted = 0"),
            postgresql_where=sa.text("NOT is_deleted"),
        )

    op.create_table(
        "memories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("zone", sa.String(), nullable=False),
        sa.Column("created_at", app.db_types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memories_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index("ix_memories_trip_created", ["trip_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_user_id"), ["user_id"], unique=False)

    op.create_table(
        "stays",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("check_in", sa.DateTime(), nullable=False),
        sa.Column("check_out", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.Column("room_type", sa.String(), nullable=True),
        sa.Column("confirmation_number", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stays", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stays_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_stays_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "travels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("carrier", sa.String(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("seat", sa.String(), nullable=True),
        sa.Column("from_location", sa.JSON(), nullable=True),
        sa.Column("to_location", sa.JSON(), nullable=True),
        sa.Column("depart", sa.DateTime(), nullable=False),
        sa.Column("arrive", sa.DateTime(), nullable=True),
        sa.Column("depart_timezone", sa.String(), nullable=True),
        sa.Column("arrive_timezone", sa.String(), nullable=True),
        sa.Column("confirmation_number", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("travels", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_travels_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_travels_trip_id"), ["trip_id"], unique=False)

    op.create_table(
        "trip_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", app.db_types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trip_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_trip_members_is_deleted"), ["is_deleted"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trip_members_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trip_members_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "uq_trip_members_trip_user_live",
            ["trip_id", "user_id"],
            unique=True,
            sqlite_where=sa.text("is_deleted = 0"),
            postgresql_where=sa.text("NOT is_deleted"),
        )

    op.create_table(
        "items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("day_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.Column("confirmation_number", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["days.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_items_day_id"), ["day_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_is_deleted"), ["is_deleted"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_items_day_id"))

    op.drop_table("items")
    with op.batch_alter_table("trip_members", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_trip_members_trip_user_live",
            sqlite_where=sa.text("is_deleted = 0"),
            postgresql_where=sa.text("NOT is_deleted"),
        )
        batch_op.drop_index(batch_op.f("ix_trip_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_trip_members_trip_id"))
        batch_op.drop_index(batch_op.f("ix_trip_members_is_deleted"))

    op.drop_table("trip_members")
    with op.batch_alter_table("travels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_travels_trip_id"))
        batch_op.drop_index(batch_op.f("ix_travels_is_deleted"))

    op.drop_table("travels")
    with op.batch_alter_table("stays", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stays_trip_id"))
        batch_op.drop_index(batch_op.f("ix_stays_is_deleted"))

    op.drop_table("stays")
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memories_user_id"))
        batch_op.drop_index(batch_op.f("ix_memories_trip_id"))
        batch_op.drop_index("ix_memories_trip_created")
        batch_op.drop_index(batch_op.f("ix_memories_is_deleted"))

    op.drop_table("memories")
    with op.batch_alter_table("days", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_days_trip_date_live",
            sqlite_where=sa.text("is_deleted = 0"),
            postgresql_where=sa.text("NOT is_deleted"),
        )
        batch_op.drop_index(batch_op.f("ix_days_trip_id"))
        batch_op.drop_index(batch_op.f("ix_days_is_deleted"))

    op.drop_table("days")
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trips_user_id"))
        batch_op.drop_index(batch_op.f("ix_trips_is_deleted"))

    op.drop_table("trips")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
