"""memories: where the phone was (lat, lng, accuracy) — Phase 31

All nullable: existing memories have no location, and an author can leave it off.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 15:28:38.263675
"""

from __future__ import annotations

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics  # noqa: F401 — the users table's GUID type
import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lat", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("lng", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("accuracy", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_column("accuracy")
        batch_op.drop_column("lng")
        batch_op.drop_column("lat")

    # ### end Alembic commands ###
