"""photos: journal photos on memories (Phase 32)

Rows only; the files live in the PhotoStore (PHOTO_DIR, a Fly volume).

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 15:41:58.424645
"""

from __future__ import annotations

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

import app.db_types

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("memory_id", sa.Uuid(), nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("original_format", sa.String(), nullable=False),
        sa.Column("original_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("created_at", app.db_types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", app.db_types.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_photos_is_deleted"), ["is_deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_photos_memory_id"), ["memory_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_photos_trip_id"), ["trip_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_photos_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_photos_user_id"))
        batch_op.drop_index(batch_op.f("ix_photos_trip_id"))
        batch_op.drop_index(batch_op.f("ix_photos_memory_id"))
        batch_op.drop_index(batch_op.f("ix_photos_is_deleted"))

    op.drop_table("photos")
    # ### end Alembic commands ###
