"""trip edit codes: the secret code that makes whoever joins an editor (Phase 40)

Nullable: a trip gets its code the first time its owner asks for it.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 17:24:41.874894
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.add_column(sa.Column("edit_code", sa.String(), nullable=True))
        batch_op.create_index("uq_trips_edit_code", ["edit_code"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trips", schema=None) as batch_op:
        batch_op.drop_index("uq_trips_edit_code")
        batch_op.drop_column("edit_code")

    # ### end Alembic commands ###
